name: New Oceanscout WISPR Data
description: Data pre-processing steps for new, incoming PAM data from Oceanscouts with WISPR recording systems. 
title: "New Seaglider WISPR Data: [INSERT DEPLOYMENT ID HERE]"
labels: ["new data"]
#projects: ["PAM SI]
assignees:
  - Kourtney-Burger
  - sfregosi-noaa
body:
  - type: input
    id: dataset-name
    attributes:
      label: Deployment ID
      description: Deployment ID from deployment tracker 
      placeholder: e.g., sg679_Aug2024
    validations: 
      required: true
      
  - type: textarea
    id: instructions
    attributes:
      label: Instructions
      description: Pre-processing instructions and method links
      value: |
        Press the green 'Create' button below to create this issue template with the data pre-processing steps for each new PAM glider dataset. More detail on these methods can be found [here](https://nmfs-ost.github.io/PAM-Glider/content/data_processing/oceanscout-wispr6.html)

  - type: checkboxes
    id: checklist_Offload-Data
    attributes:
      label: Prep Data
      description: Complete the following steps to offload the data from the WISPR board and convert it to usable audio files
      options:
        - label: Retrieve micro SD cards from the WISPR board
        - label: Copy raw .dat files from cards to a hard drive, pass hard drive off to PAM analyst 
        - label: Use agate workflow_convertWISPR.m script to convert from .dat to .flac
        - label: If .wav files are needed, use the flac2wav.m matlab script 
        
  - type: checkboxes
    id: checklist_LTSA
    attributes:
      label: LTSAs
      description: Use Matlab to create a full bandwith LTSA
      options:
        - label: Create LTSA with 5 seconds and 200 Hz settings, save LTSA as DeploymentID_SamplingRate_5s_200Hz.ltsa (ex. sg639_Sep2024_200kHz_5s_200Hz.ltsa)

  - type: checkboxes
    id: checklist_Deployment-Tracker
    attributes:
      label: Update Deployment Tracker Spreadsheet
      # description: 
      options:
        - label: Use the full bandwidth LTSA to mark data start and end (or use file timestamps) and assess overall data quality 
        - label: Calculate the deployment duration, distance, and recording duration and fill in the associated columns 
        - label: Open Glider Deployment Tracker Spreadsheet and ensure all fields have been completed

  - type: checkboxes
    id: checklist_OtherData
    attributes:
      label: Other Data
      # description: 
      options:
        - label: Extract environmental data and Oceanscout mission summary data from Hefring website
        - label: Create mission summary report